[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.flakeheaven]
format = "grouped"
max_line_length = 88

[tool.flakeheaven.plugins]
pycodestyle = ["+*"]
pyflakes = ["+*"]
"flake8-*" = ["+*"]
